# -*- coding: utf-8 -*-
"""test_unit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_Ei_1GJ2r6xx3OGDb5hpeFNHzVMf-Mf
"""

import Calculated

#from project.test.tud_test_base import mock_input_output_start, mock_input_output_end, set_input, get_output


def test_SD_check():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\FileName","Age")
    assert tes=="Please enter correct file and path and extension"


def test_SD_check1():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\FFileName.csv","Age")
    assert tes=="file does not exist"


def test_SD_check2():
    tes=Calculated.testing(r"djjhdfjhfjf","AAge")
    assert tes=="Please enter correct file and path and extension"


def test_SD_check3():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\FileName.cs","AAge")
    assert tes=="Please enter correct extension"

def test_SD_check4():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\FileName.csv","Age")
    assert tes=="S.D of this is 13.0"

def test_SD_check5():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\FileName.csv","hfhf")
    assert tes=="S.D not calculated of this column name or column doesnt exist or column held Null values or its not numberical column"

# testing for xlsx file

def test_SD_check7():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typ.xlsx","Gender")
    assert tes=="S.D not calculated of this column name or column doesnt exist or column held Null values or its not numberical column"

def test_SD_check8():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typ","Gender")
    assert tes=="Please enter correct file and path and extension"
    
def test_SD_check9():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typkk.xlsx","Gender")
    assert tes=="file does not exist"
    
def test_SD_check10():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typ.xls","Gender")
    assert tes=="Please enter correct extension"
    
def test_SD_check11():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typ.xlsx","Age")
    assert tes=="S.D of this is 8.35"
    
def test_SD_check12():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typ.xlsx","dkkdk")
    assert tes=="S.D not calculated of this column name or column doesnt exist or column held Null values or its not numberical column"

    
# testing for .json file

def test_SD_check13():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\n.json","profilePicture")
    assert tes=="S.D not calculated of this column name or column doesnt exist or column held Null values or its not numberical column"


def test_SD_check14():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\n","Gender")
    assert tes=="Please enter correct file and path and extension"
    
def test_SD_check15():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\typkk.json","Gender")
    assert tes=="file does not exist"
    
def test_SD_check16():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\n.js","Gender")
    assert tes=="Please enter correct extension"
    
def test_SD_check17():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\n.json","userId")
    assert tes=="S.D of this is 964.47"
    
def test_SD_check18():
    tes=Calculated.testing(r"C:\Users\Puneet Singh\n.json","dkkdk")
    assert tes=="S.D not calculated of this column name or column doesnt exist or column held Null values or its not numberical column"

